---
title: "Calculate your GPA"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
library(tidyverse)
library(rhandsontable)

# fix initialization errors

init <- tribble(
  ~class, ~grade, ~hours, ~major, ~include,
  "FWIS 171", "A", 3L, TRUE, TRUE,
  "LPAP 118", "A+", 1L, TRUE, TRUE,
  "CHEM 401", "B", 3L, TRUE, TRUE,
  "PHYS 345", "C-", 3L, TRUE, TRUE,
  "HUMA 304", "A+", 1L, TRUE, TRUE,
  "COMP 133", "F", 3L, TRUE, TRUE,
  "ENGL 200", "A", 3L, TRUE, TRUE,
  "SOCI 101", "A+", 1L, FALSE, TRUE,
  "CAAM 560", "A", 3L, FALSE, TRUE,
  "STAT 310", "A", 3L, FALSE, TRUE,
  "STAT 405", "A+", 4L, FALSE, TRUE,
  "MATH 221", "B", 3L, FALSE, TRUE
)
```

Column {.sidebar}
-----------------------------------------------------------------------

The most appropriate way to get a GPA on a 4.0 scale is to treat A+ grades as As. This is done by default. If you would like to see your GPA on the Rice scale, check the box below.

```{r}
checkboxInput("use_a_plus", label = "Treat A+ as 4.33 instead of 4?")
```

### Your GPA

Based on the current information, your GPA is:

- `r renderText({
paste0("Overall: ", hours_to_gpa(hours_df(hot_to_r(input$courses))))
})`

- `r renderText({
paste0("Major GPA: ", hours_to_gpa(hours_df(hot_to_r(input$courses), major = TRUE)))
})`

Column {data-width=400}
-----------------------------------------------------------------------

**Course Input**

Edit course information here by clicking the table and typing. To add a new course, right click, then select "Insert row above/below".

```{r}
letter_to_gpa <- function(letter) {
  switch(letter,
         "A+" = if (input$use_a_plus) 4.33 else 4,
         "A" = 4,
         "A-" = 3.67,
         "B+" = 3.33,
         "B" = 3,
         "B-" = 2.67,
         "C+" = 2.33,
         "C" = 2,
         "C-" = 1.67,
         "D+" = 1.33,
         "D" = 1,
         "D-" = 0.66,
         "F" = 0)
}

hours_df <- function(df, major = FALSE) {
  df <- filter(df, grade != "S", grade != "P", include)
  df <- if (major) filter(df, major) else df
  mutate(df,
         gpa_score = map_dbl(grade, letter_to_gpa),
         gpa_pts = gpa_score * hours)
}

hours_to_gpa <- function(df) {
  with(df, round(sum(gpa_pts) / sum(hours), 3))
}

rHandsontableOutput("courses")

output$courses <- renderRHandsontable({
  df <- if (is.null(input$courses)) init else hot_to_r(input$courses)
  rhandsontable(df, rowHeaders = FALSE, stretchH = "all")
})
```


Column {data-width=600}
-----------------------------------------------------------------------

### GPA Hours for included courses

```{r}
renderTable({
  hours_df(hot_to_r(input$courses))
})
```



